jobs:
  publish-template:
    # This template should exist for rest of jobs to work. Taking a shortcut
    # here
    requires: [~commit, ~pr]
    sourcePaths: ["template/"]
    image: node:8
    environment:
      SD_TEMPLATE_PATH: ./template/images-test-template.yaml
    steps:
      - install_prerequisites: npm install -g screwdriver-template-main
      - validate: template-validate
      - publish: template-publish
      - autotag: template-tag --name screwdriver-examples/images-example --tag latest
  node8:
    requires: [~commit, ~pr]
    template: screwdriver-examples/images-example
    image: node-8
  node9:
    requires: [~commit, ~pr]
    template: screwdriver-examples/images-example
    image: node-9
  node10:
    requires: [~commit, ~pr]
    template: screwdriver-examples/images-example
    image: node-10
  default-node:
    requires: [~commit, ~pr]
    template: screwdriver-examples/images-example
